// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Provides AI-driven suggestions to refine and strengthen a resume based on a job description.
 *
 * - improveResume - A function that analyzes a job description and suggests resume improvements.
 * - ImproveResumeInput - The input type for the improveResume function.
 * - ImproveResumeOutput - The return type for the improveResume function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ImproveResumeInputSchema = z.object({
  resume: z
    .string()
    .describe('The text content of the resume to be improved.'),
  jobDescription: z
    .string()
    .describe('The text content of the job description.'),
});
export type ImproveResumeInput = z.infer<typeof ImproveResumeInputSchema>;

const ImproveResumeOutputSchema = z.object({
  suggestions: z
    .string()
    .describe('AI-driven suggestions to refine and strengthen the resume.'),
});
export type ImproveResumeOutput = z.infer<typeof ImproveResumeOutputSchema>;

export async function improveResume(input: ImproveResumeInput): Promise<ImproveResumeOutput> {
  return improveResumeFlow(input);
}

const prompt = ai.definePrompt({
  name: 'improveResumePrompt',
  input: {schema: ImproveResumeInputSchema},
  output: {schema: ImproveResumeOutputSchema},
  prompt: `You are an expert resume advisor. Analyze the provided resume and job description to provide actionable suggestions on how to improve the resume to better match the job requirements.

Resume:
{{{resume}}}

Job Description:
{{{jobDescription}}}

Suggestions:
`, 
});

const improveResumeFlow = ai.defineFlow(
  {
    name: 'improveResumeFlow',
    inputSchema: ImproveResumeInputSchema,
    outputSchema: ImproveResumeOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
